lib/provider.coffee
Changed:
- 'SetPositionSmooth' and 'SetRotationSmooth' arguments to match Knowledgebase
- return type on both 'Call' snippets to variable
- type of the Player.steam_name property to string
- (minor) 'clone' and 'sticky' descriptions to match Knowledgebase
Added:
- 'admin' property to Player
- 'tooltip' property to Object
- 'broadcastToAll' function
- 'broadcastToColor' function
=> Snippets update as per Knowledgebase

lib/provider.coffee
The bulk of this is cleaning up the suggestion code, removing all the commented out properties.  I've left them in the first entry for reference, but trimmed them from every entry after; makes code a lot easier to browse.  Twice as easy, in fact, since it's half as long!
I've also changed the big blocks that create previous_token and previous_token2 to use regexp (more succint and reliable) and rewritten the conditions that do this:
`((bufferPosition.column >= 8 && editor.getTextInRange([[bufferPosition.row, bufferPosition.column - 7], bufferPosition]) == "Global.")`
to the much simpler:
`line.endsWith("Global.")`
Other changes are some minor improvements in the autocomplete logic (mostly for globals and objects).  Normally I'd wait to pull until there were more substantive upgrades, but …
=> Cleanup with some autocomplete fixes

grammars/tts_lua.cson, lib/tabletopsimulator-lua.coffee
Unicode replacement wasn't handling full range of utf-8 and wasn't handling more than one utf-8 character per line.  Fixed.
Change our temp files from .lua to .ttslua - this will stop the package being applied to non TTS Lua files.
fixes #17
fixes #5
Since we only ever operate on the temp files we make ourselves, this shouldn't have any knock-on issues with third party mods (I mean utility mods, not TTS games), at least to the best of my understanding.  Doing this means that the scope source.tts.lua will only apply to our files, and the generic scope of source.lua can be handled by another package.
=> Fixes for unicode replacement and a couple of Issues

lib/provider.coffee, lib/tabletopsimulator-lua.coffee
~~EDIT: Don't pull this quite yet, got a thing to iron out.~~
OK, we're good.
---
The autocomplete provider has a property called excludeLowerPriority; this is currently set to true.  When true the built-in autocomplete provider is disabled, meaning only the API suggestions will show up.  When set to false the built-in suggestions are provided alongside the API suggestions; these include all the identifiers the user has in their source. This is quite handy - you don't need to go looking through your code for that old global variable you can't remember the name of exactly, or exactly what you called a function a week ago.  However, it also clutters the autocomplete up a bit; having it disabled makes for a cleaner experience. i.e. there are pros and cons either way, so the user should be …
=> User setting for excludeLowerPriority, autocomplete templates for coroutines and getObjectFromGuid, settings rejig

keymaps/tabletopsimulator-lua.cson, lib/function-list-view.coffee, lib/provider.coffee, lib/status-bar-function-view.coffee, lib/tabletopsimulator-lua.coffee, menus/tabletopsimulator-lua.cson, package.json
**Added some commands to Atom:**
Goto Function (ctrl-g):
Lists all functions in program, user can filter by typing.  Hit enter or click to jump straight to function declaration.  Typing a number emulates Atom's Go To Line Number behaviour, so that keyboard shortcut can be overidden (i.e.  ctrl-g) .  Will also perform relative line-number jumps if number is prefixed with +/- (i.e. +10 will move cursor forward 10 rows)
Jump To Current Function (ctrl-shift-g):
As above, but directly from the function name the cursor is positioned on.
Select Function (ctrl-alt-<):
Same as shift-clicking the function name in the status bar; will select all the lines of the function the cursor is currently occupying.  Repeating the command will select the parent function, if applicable.
Expand Selection …
=> New Atom commands, issue #25, some experimental things

lib/tabletopsimulator-lua.coffee
If an error occured during a Save And Play, the mutex preventing multiple S&P wouldn't be reset, so the user would have to restart Atom in order to try again.  This adds a timeout on the mutex, reseting it after 3 seconds.
=> Fix for being locked out by Save And Play

lib/tabletopsimulator-lua.coffee
Linter:
- Added ability to manually suppress a warning: postfix the line with --
- Added the option to delay the linter when a file is first opened
- Better understands one-liners (now works with closing parenthesis)
- Better understands table definitions (optional comma after last item)
- Fixed the linter spamming file locks when files are opened
=> Post-update fixes

grammars/tts_lua.cson, lib/tabletopsimulator-lua.coffee
Bug where plugin would stop communicating with TTS.  
At least one cause was a problem where files were being left open when streamed to temp file from TTS; by not closing they were locked.  They were being left open because of byte miscounting, due to Sep 11th fix which split lines in the data handler over \r?\n instead of \n; have reverted this in the data handling sections.
This has fixed what is seemingly the main issue locking up the plugin; another bug found while looking for this one may also have been affecting this area (ttsEditors dictionary resetting inside the loop that adds to it instead of before).  Need to deploy this update and then await feedback; with luck this was the only issue here, but I'm not optimistic that is the case.  Added a little more logging to save routines …
=> Fix for EPERM issues

keymaps/tabletopsimulator-lua.cson, lib/tabletopsimulator-lua.coffee, menus/tabletopsimulator-lua.cson
Fixed go to line function (was going to wrong line)
Removed all '\r?' regexp which were previously inserted as a pre-emptive fix; they just broke everything they touched (see: above bug)
Added more comprehensive setting to let user decide what files are opened in Atom when they are sent from TTS.  Can also completely disable communication with TTS.
Now displays a pop-up in Atom when your TTS mod hits a run-time error, with a button to jump to offending line (if able).  Also added ```Jump To Last Error``` menu option and hotkey ```ctrl-e```.
Changed some settings so they default to on for options which have proved stable (such as the unicode conversion setting)
=> Go to line fixed, setting for automatically opening files, better runtime error reporting

keymaps/tabletopsimulator-lua.cson, lib/checkbox-list-view.coffee, lib/provider.coffee, lib/tabletopsimulator-lua.coffee, menus/tabletopsimulator-lua.cson
- TTS now fully supports utf-8, so plugin no longer converts utf-8 to \u codes (it still does the reverse if the setting is enabled)
- Open Save File command
- Generate GUID Code command (pulls GUIDs from TTS save file and makes Lua for them).  Format customizable in Style section of package settings.
- Execute Selected Lua (ctrl-@) - send whatever code you have selected to TTS.  If you're in an object script will execute under that object, otherwise will execute in Global.
- Highlight GUID Objects setting.  When enabled and your cursor is near a GUID string will make TTS highlight the related object.
- Updated autocomplete suggestions for v10.2 additions
- Fixed some linter warnings relating to comments
=> v10.2 update

lib/provider.coffee
I've added some definitions in the ``provider.coffee`` file:
* Missing ``int repetitions`` param in ``Wait.time``
* UI get/set Xml methods
* UI get/set XmlTable methods
* UI get/set CustomAssets methods
It's just the stuff I noticed is missing and no idea if just adding them there is enough, but hopefully this can save you some time.
=> Few missing methods from UI class, Wait.time repetitions param

lib/tabletopsimulator-lua.coffee
This is a very minor change that encloses `#include`d files inside `do ... end` blocks for better handling of local variables
=> Build scope for #included files

lib/tabletopsimulator-lua.coffee
This fixes the issue in #87 where having an editor that isn't file-backed open in Atom will cause Save and Play to silently fail.
=> Check to see if an editor is file backed before saving it

lib/tabletopsimulator-lua.coffee
While you can't multi-line the name normally, a script however is able to force it,  and the end result is an exception and silent failure to retrieve scripts.
=> fix exceptions caused by names having \n in them.

lib/tabletopsimulator-lua.coffee, package.json
Adds seamless support for standard Lua modules with `require(filename)` syntax.
`require()` statements are resolved when Atom saves and pushes to TTS. When this happens a bundle is generated with marker comments, much like `#include`. Unbundling occurs when we pull files from TTS, again, similar to how `#include` works.
Two new configuration options have been added to the Atom extension:
* "require() other files" toggle (default enabled, but can be disabled like `#include`)
* "Bundle file patterns", which is how Lua resolves require file paths (https://www.lua.org/pil/8.1.html). Sensible default chosen.
Files are resolved relative to the existing `includeOtherFilesPath` option, and text has been updated to reflect this.
=> Added support for require()

lib/tabletopsimulator-lua.coffee, package.json
- No more injecting comments through-out the generated Lua bundles.
- No regex magic necessary to unbundle, this behavior is delegated to luabundle; which properly parses the Lua in order to unbundle.
- Error source mapping now works correctly for bundles.
- You may now put `#include` and `require()` in the one TTS script.
However, files that are bundled as a result of a `require()` must be standard MoonSharp Lua (they cannot use `#include`) i.e. you may `#include` a file with a `require()`, but not vice versa.
=> Added support for require(): Take 2

lib/tabletopsimulator-lua.coffee, package.json
Updated `moonsharp-luaparse`, which now supports additional MoonSharp specific syntax:
- `!=` as an alternative to `~=`
- Comma separated index list i.e. `some_userdata[1, 2, 3]`
The latter of which is a MoonSharp extension that [only works for `userdata`](www.moonsharp.org/additions.html#language-differences) so is only useful if at some point Berserk want to take advantage of the syntax.
Additionally, `luabundle` has been updated and now includes custom errors (rather than just textual errors). Thus if something goes wrong during bundling/unbundling we can tell which module had the problem and the underlying cause. As a result, we now have special case handling for Lua syntax errors that are encountered during bundling. In which case we bring up a notification explaining that there's a …
=> Better require() error handling and fixed support of != syntax

lib/provider.coffee
I also saw that the `params` in spawnObject is not in the documentation, but I'm not sure if it's old or new, so I left it. If it's dead code then I'll gladly edit this to remove it as well.
=> Fixed typo in spawnObject({...})

lib/info.js, lib/tabletopsimulator-lua.coffee
Closes #126
Save & Play still fails from time-to-time on TTS end (not accepting connections), however, this at least gets us back to functional on our end.
Looks like the underlying cause is [this breaking change](https://github.com/electron/electron/pull/17298) in Electron, and Atom hasn't updated its `atom.confirm` implementation (https://github.com/atom/atom/blame/1d9a4cafcf6cc288d675512db8fd984e13aab869/src/application-delegate.js#L231-L235).
I'll submit a PR to Atom itself shortly.
=> Fix Save & Play

lib/tabletopsimulator-lua.coffee
The root module (entry point) in a luabundled script doesn't have an explicit filename, as it's not ever itself `require`'d. By default luabundle gives the root module the placeholder name `__root`, and that's the name this Atom plugin sticks with. 
When unbundling (fetching lua scripts) we do need to grab the root module and write it to a temporary file. Prior to this PR, we assumed Atom created the TTS mod, and thus we expect to find a module named `__root`.
However, [VSCode](https://github.com/rolandostar/tabletopsimulator-lua-vscode) does _not_ use the default module name `__root`, so our assumption that one exists leads to the following error when opening a mod created with the aforementioned VSCode plugin:
luabundle has built-in support retrieving the utilised root module name when …
=> Fixed handling of luabundled mods with a non-default root module name
